[package]
name = "relational_types"
description = "Manage relations between objects"
version = "2.1.1"
authors = ["Hove <core@hove.com>", "Guillaume Pinot <texitoi@texitoi.eu>"]
edition = "2021"
license = "MIT"
homepage = "https://github.com/hove-io/relational_types"
repository = "https://github.com/hove-io/relational_types"
documentation = "https://docs.rs/relational_types"
readme = "README.md"

keywords = ["relation", "collection"]

[workspace]
members = [
  "relational_types_procmacro",
  "relational_types_procmacro_tests",
]

[dependencies]
derivative = "2.2"
relational_types_procmacro = { version = "2", path = "./relational_types_procmacro/", optional = true }
thiserror = "2.0"
typed_index_collection = { git = "https://github.com/hove-io/typed_index_collection", tag = "v2.3.0"}

[features]
default = ["relational_types_procmacro"]
