name: Continuous Integration
on: [push, pull_request]

jobs:
  rustfmt:
    name: Formatting check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        components: cargo, rustfmt
    - name: Run cargo fmt
      run: |
        cargo fmt --all -- --check --color always

  clippy:
    name: Analyzing code with Clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        components: cargo, clippy
    - name: Run cargo clippy
      run: |
        cargo clippy --all-targets --all-features --workspace -- -D warnings

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        components: cargo
    - name: Run cargo test
      run: |
        cargo test --verbose --workspace
